@startuml global-workflow

skinparam ParticipantPadding 25
skinparam BoxPadding 20

'https://www.color-hex.com/color-palette/1064572
!define RED #b33a3a
!define BROWN #8c5e3c
!define ORANGE #d9a441
!define LIGHT_GREEN #6cb49b
!define DARK_GREEN #3e6b3e

box "External Service" #LightGrey
    participant Client  as Client
end box

box "Application" #White
    participant     "Spring SWIFT Exchange"     as App          DARK_GREEN
end box

box "Data" #White
    database        Redis                       as Redis        ORANGE
    database        Postgres                    as PG           ORANGE
    queue           ActiveMQ                    as MQ           ORANGE
end box

box "Files" #White
    collections     "Input Folder"              as Input        BROWN
    collections     "Unsupported Folder"        as Unsupported  RED
    collections     "Error Folder"              as Error        RED
    collections     "Success Folder"            as Success      DARK_GREEN
end box

== File reception: FileRoute ==

Client -> Input: Deliver SWIFT message file

group Camel File Listener
    App -> Input: Scan files
    Input --> App: Find new file
    App -> Redis: Ask lock on file
    
    alt LIGHT_GREEN File not already locked
        Redis --> App: Lock the file
        App -> App: Move file to ".inprogress" folder
    else RED File already locked
        Redis --> App: Lock not acquired
    end
end

== Process file: FileRoute ==

group #White Create Process

    App -> PG: Create new process\n**Database**: swiftdb\n**Table**: process\n**Status**: CREATED 
    activate PG
    PG --> App: Process ID
    deactivate PG

    App -> App: Rename file with Process ID prefix (uniqueness)

    App -> App: Encrich Camel Exchange headers

end

alt LIGHT_GREEN File extension is ".xml"
    group #White Success
        App -> MQ: Send to the validator queue\n**Queue**: swift-validator
    end

else RED Other extension
    !includesub subparts.plantuml!UnsupportedException
end 

== Validation: ValidationRoute ==

MQ o-> App: Receive message\n**Queue**: swift-validator

group Parse
    App -> App: Validate well formed

    alt LIGHT_GREEN Well formed
        group #White Validate MX
            alt LIGHT_GREEN Valid & 008.001.08
                group #White 008.001.08
                    App -> PG: Update status\n**Database**: swiftdb\n**Table**: process\n**Status**: VALIDATED 
                    App -> MQ: Send to the specific queue\n**Queue**: swift-pacs.008.001.08
                end

            else RED Invalid
                !includesub subparts.plantuml!UnsupportedException
            end
        end

    else RED Malformed
        !includesub subparts.plantuml!MalformedXmlException
    end 

end

== Specific Workflow: PACS_XXX_XXX_XXRoute ==

MQ o-> App: Receive message\n**Queue**: swift-pacs.XXX.XXX.XX

group swift-pacs.008.001.08
    App -> App: Implement your logic
    App -> PG: Update status\n**Database**: swiftdb\n**Table**: process\n**Status**: COMPLETED 
    App -> Success: Move file to the folder
end


@enduml